### ISSUE TITLE
Text styles and layer styles don't get replaced

### ISSUE THREAD

**Issue by justinspencer** [Pausansol/Camilo#10]
I have the exact same names (in both libraries) for all the symbols and styles. The symbols and nested symbols swap out perfectly however the layer styles and text styles remain unchanged. They still reference their current library.

Sketch 53

**Comment by Pausansol** [comment]
Hi justinspencer, Text and layer styles are layers or symbol overrides pointing an external library?

**Comment by Pausansol** [comment]
Released version 1.3.0 should fix this.

**Comment by justinspencer** [comment]
Works perfectly! Thanks Pausansol
