### ISSUE TITLE
Renamed symbols not swapping in "Apply to Selection" (1.4)

### ISSUE THREAD

**Issue by txcrew** [Pausansol/Camilo#13]
Hi there,

Thank you for the release of "Apply to Selection" in 1.4.

In my first test I believe to have discovered a bug when swapping art boards with multiple instances of the same master symbol, where each symbol instance has a unique name. Only the symbol with the same name as the master symbol is getting replaced.

Steps to reproduce:

1. Insert a symbol from the "master" library into an art board
2. Dduplicate the symbol, allowing sketch to rename the symbol "(master symbol name) Copy, .... Copy 2, ...Copy 3. etc."
3. Select the art board, activate Camilo and select to "Apply to Selection".

EDIT: to clarify, this only happens when there are physical symbols to swap between "master" and "brand" libraries.

Hopefully this is not by design, as this would create an additional step for designers to rename all of their symbol instances to the same master name.

Thank you again for this release!

**Comment by Pausansol** [comment]
Yes, you are right. Thanks for reporting ;) Will fix it soon.

Cheers

**Comment by Pausansol** [comment]
Fixed
