### ISSUE TITLE
Symbol gets deleted

### ISSUE THREAD

**Issue by mlangsman** [Pausansol/Camilo#17]
This is an awesome plugin - great work! 

I have found one issue however....

My project organization is as follows : 

Brand Libraries -> Component Library -> Master

To switch brands I go to my components library and run the plugin. All the symbols and type styles in my components switch fine except one artboard which gets entirely deleted...

The item is an illustration for which I have a different version in each brand. It sits on it's own artboard in components. When I switch brands the artboard just goes :(

This only happens when I select the 'Apply to Document' radio in the plugin. If I select the illustration and 'Apply to Selection' in swaps fine.

<img width="1489" alt="Screenshot 2019-04-01 at 16 19 26" src="https://user-images.githubusercontent.com/936826/55340344-66edc280-549c-11e9-9f04-db2ed8370b86.png">
<img width="1489" alt="Screenshot 2019-04-01 at 16 24 10" src="https://user-images.githubusercontent.com/936826/55340350-6b19e000-549c-11e9-9761-f66527129758.png">

Be great to hear if you have any thoughts on this!

**Comment by Pausansol** [comment]
humm, it will help if you can isolate the "thing" and send the files to me. I will look a it if i find the issue.

Thanks
