### ISSUE TITLE
Add to preserve layer opacity

### ISSUE THREAD

**Issue by abinashmohanty** [Pausansol/Camilo#30]
Whenever we replace a symbol library, it replaced a set of layers from the selected library styles. But it forgets to preserve its opacity, and hence everything becomes filled as 100%. The problem is some of its nested elements having the same colors get merged. The example below has two layers, both of them are having the same color styles but the difference in opacity. So after applying camilo, the icon gets merged with its outer circle due to same color. If we can retain the color opacity it could solve the problem.

![image](https://user-images.githubusercontent.com/8434934/85583199-ac774c00-b65b-11ea-8864-c5eac1a0d1b8.png)

**Comment by Pausansol** [comment]
I'm afraid it's not possible since that way it wouldn't work in all scenarios. I recommend you to create a new layer style for that icon background.
