### ISSUE TITLE
Include Color variables in the switch

### ISSUE THREAD

**Issue by ivogomes** [Pausansol/Camilo#32]
Sketch 69 introduced color variables. This is a great way to have themes in separate libraries.
However, when using Camilo, it doesn't replace the color variables.

**Comment by Jorriknauta** [comment]
Would also like to see this implemented 👍

**Comment by danieliustv** [comment]
Hi @Pausansol , after installing the v2 update, the plugin stopped working, I can't toggle on its window anymore. Tried uninstalling the old version and installing a v2 from scratch.

**Comment by Pausansol** [comment]
Sketch version and macOS version?

**Comment by danieliustv** [comment]
> Sketch version and macOS version? El El jue, 5 nov 2020 a las 14:32, danieliustv <notifications@github.com> escribió:
> […](#)

Sketch 69.2 (107504), Mojave 10.14.6 (18G4032)

**Comment by Pausansol** [comment]
I released a new version 2.0.1 with a bug fixed. Can you try the new one?

**Comment by danieliustv** [comment]
> I released a new version 2.0.1 with a bug fixed. Can you try the new one?

Thanks, it does work!! Does a v2 supports the color variables?

**Comment by Pausansol** [comment]
Not yet, but it will be ready soon

**Comment by icona79** [comment]
Hi @Pausansol, any news on this? 👍

**Comment by hoonch** [comment]
Hello @Pausansol - amazing plugin!!!  I am also interested if any updates to this colour task.

Just to note it would great for the colour variables be linked to the self contained document itself, currently the layer styles do swap out the colour swatch but they reference directly the library file ( hosted locally / or cloud )

**Comment by bmooij-lg** [comment]
Is this still in progress? As I'm very interested in this _enhancement_ it would allow for styling of components/icons ect in designs which would swap style per theme, without having to create all variations in each theme.

**Comment by vkoopmans-resoluut** [comment]
+1 on this one, color variables in sketch is the enhancement that would make this plugin even better!

**Comment by Pausansol** [comment]
Hi all, thank you for your interest. I'm gonna release a new version with color variables features this week. Stay tuned. Thank you again for your support.

**Comment by Pausansol** [comment]
Released :) Please, report any issues related to color vars feature in another thread. Thank u all for your support.
