### ISSUE TITLE
Swap foreignLayerStyles and foreignTextStyles overrides between libraries

### ISSUE THREAD

**Issue by yceballost** [Pausansol/Camilo#4]
Hi!

It's would be nice the possibility to connect text & layer styles from other libraries in symbols override.

By the moment, when I try to update the name of a style, (Ex: **Style_1** to **Style_2**) the plugin can't identify the change and my workflow breaks.

Anyway, great job!! 
Thanks!!

**Comment by Pausansol** [comment]
Hi @yceballost, we realized this is a must for our plugin and we are currently developing this feature.

Thanks for the feedback

**Comment by jonmh85** [comment]
This feature would be so useful! I have been looking for this since sketch added styles to libraries. 

At the moment I work on a master file and then place the full templates as library symbols in a separate file for each brand/theme. Changing the the style overrides individually is a nightmare. This would be a life saver.

**Comment by Pausansol** [comment]
Hi @jonmh85, I'm glad to know that it will be useful for more people. You will like to know that we are working on it and we will make a release with this functionality before EOY.

**Comment by Reac89** [comment]
thanks @Pausansol for this beautiful plugin! The recent trend around libraries is to split them into multiple Sketch files so it would be perfect if your plugin could work with nested libraries!!

**Comment by Pausansol** [comment]
@Reac89 thanks for the feedback. This feature is currently [in review](https://github.com/Pausansol/Camilo/projects/1).

Cheers

**Comment by Pausansol** [comment]
Issue closed, plugin version released with this new killer feature ;)

Cheers,
Pablo

**Comment by pterisaur** [comment]
This feature doesn't seem to be working anymore — style overrides in symbols are no longer replaced.
