### ISSUE TITLE
Swap foreignStyles from text and shape layers

### ISSUE THREAD

**Issue by Doson80** [Pausansol/Camilo#8]
Camilo seems the plugin that we are waiting for but I've tried it with Sketch 52.6 and it doesn't work..., even the example file. Any upgrade?

**Comment by Pausansol** [comment]
Tried with all example files and working in 52.6. Can you describe the process you have followed to try to reproduce it?

**Comment by Doson80** [comment]
Ok I've found which was my mistake, there is no "UI kit" file inside the example folder after the download so I was trying to work in the "masterLibrary" file and obviously the override didn't work, so I created an extra file in which import the elements from library and now it works. THANK YOU :)

**Comment by Pausansol** [comment]
You are welcome ;)

**Comment by Doson80** [comment]
Your plugin works well with the symbols overrides but it would be nice and useful for us if the swap would work even on layer and text styles directly instanced with the same name, in short terms if the plugin would works directly in the "master library" file it would be perfect. Do you think is a possible enhancement?

**Comment by Pausansol** [comment]
Yes, it is possible. We will add it to the roadmap. Thank you

**Comment by Pausansol** [comment]
Done
