### ISSUE TITLE
Switching libraries does not preserve overrides on parallel text styles

### ISSUE THREAD

**Issue by kemch** [Pausansol/Camilo#9]
Hey there,
When switching to another library, the plugin correctly switches out the local (or library) text styles for the target library text style, but it "resets" any overrides that may have been applied. For design files that have the occasional one-off override, like centered text for example, they'll be reset resulting in manually having to reapply them.

I think preserving these overrides when switching would be desirable behavior, especially if the overrides were intentional.
Thanks

**Comment by Pausansol** [comment]
Not sure what you mean with "parallel text styles". Maybe you have different styles with the same name?

**Comment by kemch** [comment]
I'm just referring to the same text style between the 2 libraries. When the plugin applies the text style of the same, it clears any overrides that may have been applied to that text layer.

**Comment by Pausansol** [comment]
oh! I understand now. Text styles doesn't work that way in sketch. Unfortunately, those parameters are part of the style, they are not overrides. That is the reason most designers do different styles for different alignments. [Take a look](https://medium.com/sketch-app-sources/text-styles-mastery-with-sketch-52-dc00c7fe1aa6)
